site_name: US ATLAS Analysis Facilities
site_description: Documentation for UChicago Analysis Facility (AF)
site_author: USATLAS
site_url: https://usatlas.readthedocs.io/projects/af-docs/
repo_name: usatlas/AFdocs
repo_url: https://github.com/usatlas/AFdocs
edit_uri: edit/main/docs
copyright: "Copyright &copy; USATLAS 2025-present"

docs_dir: docs
site_dir: site
theme:
  name: material
  logo: images/lgbt_atlas.png
  favicon: images/lgbt_atlas.png
  font: false
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

extra_css:
  - css/atlas-theme.css

extra_javascript:
  - javascript/config.js
  - https://polyfill-fastly.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
      - Introduction: README.md
      - FAQs and Tips: faqs_tips.md

  - Need Help?: getting_help.md

  - Computing and Access:
      - computing/index.md
      - About the Facilities: computing/facilities.md
      - Signing Up:
          - BNL: bnl/account.md
          - UChicago: uchicago/account.md
          - SLAC: slac/account.md
      - Accessing:
          - SSH Guide: computing/ssh_guide.md
          - BNL: bnl/accessing.md
          - UChicago: uchicago/accessing.md
          - SLAC: slac/accessing.md
      - Running Jobs:
          - BNL: bnl/batch.md
          - UChicago: uchicago/batch.md
          - SLAC: slac/batch.md
    - Data:
        - Storage:
            - BNL: bnl/storage.md
            - UChicago: uchicago/storage.md
            - SLAC: slac/storage.md
        - Sharing:
            - BNL: bnl/data_sharing.md
            - UChicago: uchicago/data_sharing.md
            - SLAC: slac/data_sharing.md
        - XCache:
            - BNL: bnl/xcache.md
            - UChicago: uchicago/xcache.md
            - SLAC: slac/xcache.md
        - EOS:
            - BNL: bnl/eos.md
            - UChicago: uchicago/eos.md

  - Software & Tools:
      - Containers:
          - Machine Learning:
              - Info: containers/ml/info.md
              - Contents: containers/ml/contents.md
              - Implementing: containers/ml/implement.md
          - ATLAS Analysis:
              - OS Containers: containers/atlas/os.md
              - Release Containers: containers/atlas/release.md
          - Singularity:
              - Introduction: containers/singularity/introduction.md
              - Installation: containers/singularity/installation.md
              - Usage: containers/singularity/usage.md
              - Images: containers/singularity/images.md
              - Grid Jobs: containers/singularity/grid.md
      - Jupyter:
          - Overview: jupyter/info.md
          - Access per Site:
              - BNL: bnl/jupyter.md
              - UChicago: uchicago/jupyter.md
              - SLAC: slac/jupyter.md
          - Advanced:
              - Coffea on UChicago: uchicago/jupyter_coffea.md
              - Extending on SLAC: slac/jupyter_extra.md
          - Examples:
              - xAOD Check: jupyter/examples/xAODcheck.md
              - Read xAOD with PyROOT: https://github.com/usatlas/docs/blob/master/jupyter/examples/pyROOT_example.ipynb
              - Uproot Variable Conversion: jupyter/examples/convert_specific_variables.py.txt
      - AI Inference:
          - Triton (UChicago):
              - User Guide: uchicago/triton.md
              - Deployment Notes: uchicago/triton_deployment.md
      - Development Tools:
          - Using VSCode: tools/vscode.md

  - Tutorials:
      - Overview: tutorials/201908/info.md
      - BNL Examples: tutorials/201908/bnl.md
      - SLAC Examples: tutorials/201908/slac.md
      - Grid Examples: tutorials/201908/grid.md

not_in_nav: |
  /LLM/README.md
  /LLM/RunYourOwnOllama.md
  /LLM/SharedLLMservice.md
  /ML-Containers/ML-Containers/README.md
  /ML-Containers/ML-Containers/ml-images-ReadMe.md

plugins:
  # Built-in
  search: {}
  macros: {}
  # Extra
  table-reader: {}
  glightbox: {}
  git-revision-date-localized:
    type: date
    # Required for generated documentation from gen-files
    fallback_to_build_date: true
  section-index: {}
  minify:
    minify_html: true

markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  # disable in favor of pymdownx.blocks.admonition
  #- markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
      mode: accept
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: cern
      custom:
        cern:
          host: https://gitlab.cern.ch
          label: GitLab
          type: gitlab
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
        - docs/README.md
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.blocks.admonition:
  - pymdownx.tilde:
  - attr_list:
  - md_in_html:
  - pymdownx.blocks.caption:
